#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          stream
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts mjpeg video stream
# Description:	     Starts mjpeg video stream on 172.24.1.1:8080
### END INIT INFO

# Author: Mark Scarcella <mark.scarcella@maas.museum>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modif

case "$1" in 
    start)
        echo "Starting stream"
	mkdir /tmp/stream
	raspistill -bm -vf -hf --nopreview -w 640 -h 480 -q 5 -o /tmp/stream/pic.jpg -tl 0 -t 9999999 -th 0:0:0 &
	export LD_LIBRARY_PATH=/usr/local/lib
	/usr/local/bin/mjpg_streamer -i "input_file.so -f /tmp/stream -n pic.jpg" -o "output_http.so -w /usr/local/www"&
        ;;
    stop)
        echo "Stopping stream"
	rm -rf /tmp/stream
        killall raspistill
	killall mjpg_streamer
        ;;
    *)
        echo "Usage: /etc/init.d/stream start|stop"
        exit 1
        ;;
esac

exit 0
